// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts", "src/cli.ts", "bin/*.{ts,js}"],
    project: ["src/**/*.ts", "bin/**/*.{ts,js}"],
    ignoreDependencies: ["@adddog/design-tokens"],
    ignore: [
        "constants.ts",
        "design-tokens.config.ts",
        "src/tokens/color/**",
        "src/tokens/shared/**",
    ],
    includeEntryExports: true,
    rules: {
        exports: "off",
        types: "off",
    },
});
